### ISSUE TITLE
#3 - Create a nav bar with dummy pages

### ISSUE THREAD

**Issue by cenarturkmen** [cenarturkmen/usk-memories#3]

**Comment by mutluhanuzmez** [comment]
Can I work on that issue? It seems easy to start :) I can't assign myself to the issues, maybe I need to be invited to the project.

**Comment by cenarturkmen** [comment]
Yes, there is no info about what we need about the navigations. You can just feel free to do things. There is an old blogspot website, maybe this can help you with what is this USK thing.
http://urbansketchersistanbul.blogspot.com/
